* Climate emulator and its applications to economic analysis

** Data processing

Retrieve raw CMIP data for surface air temperature (~tas~), incoming shortwave radiation (~rsdt~), outgoing shortwave radiation (~rsut~),
outgoing longwave radiation (~rlut~), and grid cell area (~areacella~) from the [[https://esgf.llnl.gov/][Earth System Grid Federation]].
Download data associated with the following experiments: ~piControl~, `abrupt-2xCO2`, `abrupt-4xCO2`, ~1pctCO2~, ~historical~, ~ssp119~, ~ssp245~, ~ssp370~, ~ssp460~, and ~ssp585~.
Save the downloaded files to the ~./data_raw/CMIP6~ directory.

Next, process the temperature and radiation data to generate global-mean time series, outputting the results as .csv files. This can be done using the provided Python script:
#+begin_src python
python process_cmip_data.py [--model_id MIROC6]
#+end_src
The ~--model_id~ argument allows for specifying a particular climate model, with ~MIROC6~ as the default.

** Plotting experimental data

After preprocessing the CMIP data, visualizations can be generated to examine the results. For example:
#+begin_src shell
python plot_experiment_tas.py [--model_id MIROC6]
#+end_src

[[./output/fig_plot_experiment_tas.svg]]

#+begin_src shell
python plot_historical_tas.py [--model_id MIROC6]
#+end_src

[[./output/fig_plot_historical_tas.svg]]

#+begin_src shell
python plot_scenario_tas.py [--model_id MIROC6]
#+end_src

[[./output/fig_plot_scenario_tas.svg]]

The generated figures will be stored in ~./output~ directory.

** Climate emulator

The model is a two-layer energy balance model a la [[https://doi.org/10.1175/JCLI-D-19-0589.1][Cummins, Stephenson, Stott (2020)]].
We calibrate the model based on the ~abrupt-4xCO2~ experiment:

#+begin_src shell :results output :exports both
python calibrate_emulator.py [MIROC6]
#+end_src

#+RESULTS:
#+begin_example
-- Nelder-Mead (Best method) --
 fvalue: 5.81538625461283 (attempt 1)
 status: Success in 20.535226821899414 seconds
 message: Optimization terminated successfully.
 estimated parameters (vs initial guess):
  1.8550 +-0.4758 (1.9937)
  4.5689 +-0.8068 (5.1617)
  354.4272 +-62.7558 (356.3721)
  1.5986 +-0.1792 (1.4604)
  1.0627 +-0.0882 (1.0577)
  0.4566 +-0.1749 (0.3517)
  0.7309 +-0.0923 (0.7535)
  0.9718 +-0.1588 (1.0787)
  0.0000 +-1.7548 (0.5765)
  10.4459 +-0.8570 (9.6197)
#+end_example

The estimated parameter values of the model will be stored in ~./output~ directory.

#+begin_src shell :results output :exports both
cat ./output/parameter_MIROC6_abrupt-4xCO2_r1i1p1f1.csv
#+end_src

#+RESULTS:
#+begin_example
parameter,value
gamma,1.854986624583049
chi1,4.5689113459737865
chi2,354.4271598484283
kappa1,1.5986036054916877
kappa2,1.0626953280905416
epsilon,0.45658815881797343
sigma1,0.7309323634764261
sigma2,0.9717890994755948
sigma3,5.887261283027005e-06
Fbar,10.445851486241933
#+end_example

Evaluate the internal validity (against ~abrupt-4xCO2~)
and the external validity (against ~historical~, ~ssp119~, ~ssp245~, ~ssp370~, ~ssp460~, ~ssp585~)
of the calibrated model:

#+begin_src shell
python evaluate_emulator.py [--model_id MIROC6]
#+end_src

[[./output/fig_evaluate_emulator.svg]]

** References

- Barrage, L., & Nordhaus, W. (2024). [[https://doi.org/10.1073/pnas.2312030121][Policies, projections, and the social cost of carbon: Results from the DICE-2023 model]]. Proceedings of the National Academy of Sciences of the United States of America, 121(13), e2312030121.
- Bauer, M. D., & Rudebusch, G. D. (2023). [[https://doi.org/10.1162/rest_a_01109][The rising cost of climate change: Evidence from the bond market]]. The Review of Economics and Statistics, 105(5), 1255–1270.
- Cummins, D. P., Stephenson, D. B., & Stott, P. A. (2020). [[https://doi.org/10.1175/JCLI-D-19-0589.1][Optimal Estimation of Stochastic Energy Balance Model Parameters]]. Journal of Climate, 33(18), 7909–7926.
- Joos, F., Roth, R., Fuglestvedt, J. S., Peters, G. P., Enting, I. G., Bloh, W. von, Brovkin, V., Burke, E. J., Eby, M., Edwards, N. R., & Others. (2013). [[https://acp.copernicus.org/articles/13/2793/2013/][Carbon dioxide and climate impulse response functions for the computation of greenhouse gas metrics: a multi-model analysis]]. Atmospheric Chemistry and Physics, 13(5), 2793–2825.
- Meinshausen, M., Nicholls, Z. R. J., Lewis, J., Gidden, M. J., Vogel, E., Freund, M., Beyerle, U., Gessner, C., Nauels, A., Bauer, N., Canadell, J. G., Daniel, J. S., John, A., Krummel, P. B., Luderer, G., Meinshausen, N., Montzka, S. A., Rayner, P. J., Reimann, S., Smith, S. J., van den Berg, M., Velders, G. J. M., Vollmer, M. K., and Wang, R. H. J. (2020). [[https://doi.org/10.5194/gmd-13-3571-2020][The shared socio-economic pathway (SSP) greenhouse gas concentrations and their extensions to 2500]]. Geoscientific Model Development, 13, 3571–3605.
- MPD version 2023: Bolt, Jutta and Jan Luiten van Zanden (2024). [[http://doi.org/10.1111/joes.12618][Maddison style estimates of the evolution of the world economy: A new 2023 update]]. Journal of Economic Surveys, 1–41.
- Osborn, T.J., Jones, P.D., Lister, D.H., Morice, C.P., Simpson, I.R., Winn, J.P., Hogan, E., and Harris, I.C., (2021). [[https://doi.org/10.1029/2019JD032352][Land surface air temperature variations across the globe updated to 2019: the CRUTEM5 dataset]]. Journal of Geophysical Research: Atmospheres. 126, e2019JD032352,
- Kevin Rennert, Brian C. Prest, William A. Pizer, Richard G. Newell, David Anthoff, Cora Kingdon, Lisa Rennels, Roger Cooke, Adrian E. Raftery, Hana Ševčíková, & Frank Errickson. (2022). [[https://doi.org/10.5281/zenodo.6016583][Resources for the Future Socioeconomic Projections (RFF-SPs) (Version 5) [Data set]​]]. Zenodo.
- Smith, Christopher J. (2019, October 21). [[http://doi.org/10.5281/zenodo.3515339][Effective Radiative Forcing from Shared Socioeconomic Pathways (Version v0.3.1)]]. Zenodo.
- Tatebe, Hiroaki; Watanabe, Masahiro (2018). [[https://doi.org/10.22033/ESGF/CMIP6.881][MIROC6 model output prepared for CMIP6]]. Earth System Grid Federation.
- World Bank. [[https://data.worldbank.org/indicator/NY.GNS.ICTR.ZS][Gross savings (% of GDP) World Development Indicators]]. The World Bank Group.
- Zebedee Nicholls, & Jared Lewis. (2021). [[https://doi.org/10.5281/zenodo.4589756][Reduced Complexity Model Intercomparison Project (RCMIP) protocol (v5.1.0) [Data set]​]]. Zenodo.
